### PR TITLE
Feature to master branch

### PR DESCRIPTION
**Pull request by glowreeyah**
# In this project I focused on using bootstrap:

- I used bootstrap classes for my layout.
- I focused on making it mobile responsive.
- It is responsiveness for all screen sizes

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @glowreeyah :clap: :clap:
#### You did an incredible job :+1: . The page looks great but there are few requirements you need to fix or implement before the project can be approved. :point_down: 

**_1. Fix the image in the subscribe section to look like the original (the image on top is smaller, so, make it the same size of the image behind it)._**

**_2. Fix the position of the texts below the images in the "INTHE MAGAZINE" section. They seem to overlap._**

**_The Newsweek logo should be white._**

**_Kindly fix these and submit for review._**

### _Review by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by lekegitrepo** [comment]
#### Hi @glowreeyah :clap: 
#### Good job :+1:  for implementing required changes specify in my previous review. However, you have not fixed the problem in the "IN THE MAGAZINE" section that I mentioned in the previous review. Check the image below :point_down: 

**_This happens at 768px and less screen sizes:_**

Screenshot from 2020-04-20 05-28-13

 **_Try to fix this_**

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by glowreeyah** [comment]
Hi, @lekegitrepo 
I apologise, I did not notice that part. I have made the necessary corrections now.

**Comment by uryelah** [comment]
Hello **Glory David David-Akubo**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job fixing that one last required change. 

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----


**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
